### ISSUE TITLE
Slider to choose figure height/width in "curstomize additional other features of the plot" is hardly adjustable to a certain value

### ISSUE THREAD

**Issue by NinaSchukraft** [DSegebarth/dcl_stats_n_plots#10]

**Comment by DennisDoll** [comment]
Upon clicking on the slider, you can use your keyboard's arrow keys to move the slider in a stepwise manner. Let me know if this already solving the issue or whether we should switch to a different widget!

**Comment by NinaSchukraft** [comment]
Ah, didn't know this trick, that's fine then!
