### ISSUE TITLE
Tab 'Customize annotations' -  Distance of annotations/stars doesn't correlate to chosen value

### ISSUE THREAD

**Issue by NinaSchukraft** [DSegebarth/dcl_stats_n_plots#11]
Distance in plot gets smaller the higher you put the value + if distance is set to an value and you update the plot, the value changes in the customazitaion tab

**Comment by DennisDoll** [comment]
This seems really strange. Values specified by the user should only be overwritten, when the "update to uploaded settings" button in the "customize your plot" tab is clicked, but not if the "update the plot" in the "generated plot" tab is clicked. 

Could you also add some more details on when this behavior occurred? Unfortunately I was not able to reproduce it :/ 

For instance, if I change "Distance of the stars to the annotation bars" from 0 to 3, they also move accordingly:
Set to 0:
![grafik](https://user-images.githubusercontent.com/64020372/168400429-2216a8f3-f2fc-4512-b8ad-d58a7851665e.png)

Set to 3:
![grafik](https://user-images.githubusercontent.com/64020372/168400501-65a24a3d-73d7-4896-b6dc-f1b702e904ef.png)

Likewise, when I change the "Distance of the annotation bars to the graph", the annotation bars also move accordingly. However, please note that the "Distance of the stars to the annotation bars" is also calculated in a function of the "Distance of the annotation bars to the graph", where the stars distance is higher, the higher the annotation bars distance is. Unfortunately, this has to be corrected manually, if unwanted, by changing the "Distance of the stars to the annotation bars" *after* adjusting the "Distance of the annotation bars to the graph". 

"Distance of the annotation bars to the graph" set to 0:
![grafik](https://user-images.githubusercontent.com/64020372/168400724-b55e7163-6dbb-4b30-8645-01ffc5056bd2.png)

"Distance of the annotation bars to the graph" set to 3:
![grafik](https://user-images.githubusercontent.com/64020372/168400881-85e9ad04-8c2c-47a9-a37f-7a2836f73e26.png)

"Distance of the annotation bars to the graph" set to 3 and adjusted the "Distance of the stars to the annotation bars" from 3 to 0.4:
![grafik](https://user-images.githubusercontent.com/64020372/168401088-691b2898-42e3-4446-bb26-80fb5fafffd7.png)


This was confirmed for all three plot types that are currently implemented (MMA, pairwise comparison of independent samples, one sample test). Please let me know if the bug you described persists or if this issue can be closed.

**Comment by NinaSchukraft** [comment]
As I understood these values as absolute distance, I have used them in the wrong way. (I guess it always changed back to 1, since this is the max. value). Got it now!
