### ISSUE TITLE
Axis labelings break down when plot is too small

### ISSUE THREAD

**Issue by DennisDoll** [DSegebarth/dcl_stats_n_plots#5]
Y-axis gets cut & x-axis tick-labels start to overlap if the size of the plot is set to smaller sizes (paper or thesis configuration).

Suggested solutions: rotations of the axis? or labeling with line breaks?

Reported by N. Schukraft

**Comment by NinaSchukraft** [comment]
in the GUI even small plots are displayed perfectly, only after exporting the plot it is cut on left and lower side
